### ISSUE TITLE
Standard Local Env Vars / Local database

### ISSUE THREAD

**Issue by huntercross** [ponticlaro/docker-templates#2]
Possible to have a standard local user for database setup, so that the majority of local development can use the built-in environment?

This would obviously get overridden in production, but it would be nice if on first checkout, if you have the name of the project as a database properly defined (i.e. if the project name is aia-austin-www, then if you have a database called aia-austin-www and it is available at the standard local mysql port, etc. it can be accessed, either through root:root or whatever you think is best...

Would also be nice to be able to have a db folder setup where a db would be loaded if it is there

**Comment by cristianobaptista** [comment]
### Dev Database
The default (which is also the dev one) docker-compose.yml also starts a [mysql server](https://github.com/ponticlaro/docker-templates/blob/master/php-stacks/docker-compose.yml#L12-L18) with **root** as the user, no password and **dev** as the database name. Within containers this mysql server can be accessed with this URL: `mysql://root:@mysql/dev`

### Staging/Production Database
[Staging](https://github.com/ponticlaro/docker-templates/blob/master/php-stacks/docker-compose.staging.yml) and [Production](https://github.com/ponticlaro/docker-templates/blob/master/php-stacks/docker-compose.production.yml) docker-composer.yml scripts do not start a mysql server.

### Importing remote database to dev mysql server
After running `docker-compose up -d` you can use the **app** container to import a remote database like this:

```
docker-compose run app mysql-import -r mysql://user:pass@host/database_name
```

I probably need to add a way to import a database dump on the local filesystem

**Comment by cristianobaptista** [comment]
This feature is documented on the [README](https://github.com/ponticlaro/docker-templates/tree/master/php-stacks#mysql-import)
